### PR TITLE
2022 Database Seeding

### PR DESCRIPTION
**Pull request by Sherlouk**
This feeds into #72, and will rebase as necessary once that gets merged in. This pull request will expand on the seeding capability by providing a dump of the 2022 schedule/sponsors/etm.

Part of this is also replacing many of the hard-coded URLs with a new 'awsImage' leaf tag which is powered by the existing environment variable.

Manual Seeding Progress (from 2022 Data)

- [x] Activities
- [x] Events
- [x] Location Categories
- [x] Locations (Partial)
- [x] Presentations
- [x] Slots
- [x] Speakers
- [x] Sponsors

### CODE REVIEW

**Comment by Sherlouk** [comment]
Just the locations need finishing, but something about copying and pasting a tonne of coordinates at 1am to really send me crazy. So I'll do it in the morning 😛  (unless @adamrushy wants to just finish it off with the proper DB contents)

Will rebase/change base into `develop` once first PR goes through. Last 4 commits here are what's been changed, namely the introduction of seed.sql.

**Comment by Sherlouk** [comment]
Fixed line breaks, finished locations (JSON to CSV to the rescue), and tested end-to-end. Users can now seed their tables (will wipe any data already there) and it has parity with what we have in production right now giving a good foundation to work from.

**Comment by Sherlouk** [comment]
@adamrushy @pdamonkey 

What's merge policy like here (especially now I'm a member 👀)

Do we self merge once approved and no open discussions? or does someone else merge?

**Comment by pdamonkey** [comment]
You merge yourself once reviewed and no outstanding discussions. If you can merge the other PR and catch this one up, I'll give it a review too.

**Comment by Sherlouk** [comment]
PR has been rebased (@pdamonkey). It would be handy if someone aside from me could run the seed command just to make sure it's working (take a backup of your database first, especially if you already have custom data in there, as this will wipe existing data!)

**Pull request merged**
