### PR TITLE
Update AND Digital logo

### PR DESCRIPTION
**Pull request by lukestringer90**
Use a updated version of the AND Digital logo for the sponsors section.

### CODE REVIEW

**Comment by lukestringer90** [comment]
@adamrushy Any chance you could check this looks ok? I've run the Vapor app locally and the new logo looks to be rendering fine.

**Comment by adamrushy** [comment]
@lukestringer90 looks good, but can you screenshot all the different size variations with the rendered version?

**Comment by lukestringer90** [comment]
@adamrushy Sure. Do you want me to screenshot them and attach them to this PR so you can confirm it looks good?

**Comment by adamrushy** [comment]
> @adamrushy Sure. Do you want me to screenshot them and attach them to this PR so you can confirm it looks good?

Yes please 👍🏼

**Comment by lukestringer90** [comment]
Screenshot 2022-04-05 at 13 13 54
Screenshot 2022-04-05 at 13 13 57
Screenshot 2022-04-05 at 13 13 44
Screenshot 2022-04-05 at 13 13 50
Screenshot 2022-04-05 at 13 13 39
Screenshot 2022-04-05 at 13 13 34

**Review by pdamonkey — APPROVED** [review]

**Comment by lukestringer90** [comment]
Thanks @adamrushy 😄

**Pull request merged**
